### ISSUE TITLE
Add name service contract

### ISSUE THREAD

**Issue by ethanfrey** [confio/cosmwasm-examples#23]
This is defined in https://www.cosmwasm.com/docs/name-service/intro

We should code this, film the coding ideally, and then add it to the tutorial.

**Comment by clevinson** [comment]
Draft PR here: #30 

Once we have consensus on the PR, i'm happy to write up a tutorial and do a short video of writing it up from scratch.

**Comment by ethanfrey** [comment]
Closes by #30 and #31 

Thanks for this. Happy for any docs or video write ups you add.
