### ISSUE TITLE
Use more condense binary representation for escrow state

### ISSUE THREAD

**Issue by webmaster128** [confio/cosmwasm-examples#39]
I just saw that the binary representation of the fields in an escrow state is very long

```json
{"verifier":[13,130,177,231,201,109,191,164,36,98,254,97,41,50,230,191,241,17,213,27],"beneficiary":[81,69,45,155,60,246,246,131,76,249,170,151,193,37,3,215,22,22,229,213],"funder":[13,130,177,231,201,109,191,164,36,98,254,97,41,50,230,191,241,17,213,27]}
```

If storage is the most expensive thing in the system, we should better use base64 here.

**Comment by ethanfrey** [comment]
Yes, as soon as we have cosmwasm 0.7, we should definitely fix this up
